---
- name: Apply LazyLibrarian
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig_path }}"
    namespace: argocd
    definition: "{{ lookup('file', playbook_dir + '/argocd/applications/media/lazylibrarian/lazylibrarian-application.yaml') }}"

