---
- name: Apply Threadfin
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig_path }}"
    namespace: argocd
    definition: "{{ lookup('file', playbook_dir + '/argocd/applications/media/threadfin/threadfin-application.yaml') }}"
  tags: [threadfin]

