---
- name: Apply Immich Restore Test Configuration
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig_path }}"
    namespace: argocd
    definition: "{{ lookup('file', playbook_dir + '/argocd/applications/media/immich-restore-test/immich-application.yaml') }}"
  tags: immich-restore-test

