apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: obsidian-livesync-ingress
  namespace: obsidian
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - obsidian.soyspray.vip
      secretName: obsidian-livesync-tls
  rules:
    - host: obsidian.soyspray.vip
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: obsidian-livesync-svc-couchdb
                port:
                  number: 5984

