apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: obsidian

helmCharts:
  - name: couchdb
    version: 4.6.2
    repo: https://apache.github.io/couchdb-helm
    releaseName: obsidian-livesync
    namespace: obsidian
    valuesFile: values.yaml

resources:
  - ingress.yaml

