---
- name: Apply Alert Test
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig_path }}"
    namespace: argocd
    definition: "{{ lookup('file', playbook_dir + '/argocd/applications/observability/alert-test/alert-test-application.yaml') }}"

