---
- name: Apply Longhorn
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig_path }}"
    namespace: argocd
    definition: "{{ lookup('file', playbook_dir + '/argocd/applications/infrastructure/longhorn/longhorn-application.yaml') }}"

