apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - loki-serviceaccount.yaml
  - loki-configmap.yaml
  - loki-rules-kubernetes.yaml
  - loki-rules-backup.yaml
  - loki-service.yaml
  - loki-statefulset.yaml
  - loki-servicemonitor.yaml
  - alloy-rbac.yaml
  - alloy-configmap.yaml
  - alloy-daemonset.yaml
  - alloy-podmonitor.yaml
  - alloy-events-configmap.yaml
  - alloy-events-deployment.yaml
