# playbooks/argocd/applications/media/booklore/booklore-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: booklore-db-secret
  namespace: media
type: Opaque
data:
  # booklore123
  db-password: Ym9va2xvcmUxMjM=
  db-user: Ym9va2xvcmU=
  db-name: Ym9va2xvcmU=
