# playbooks/argocd/applications/media/booklore/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: booklore
  namespace: media
  labels:
    app: booklore
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "500m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - booklore.soyspray.vip
      secretName: prod-cert-tls
  rules:
    - host: booklore.soyspray.vip
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: booklore
                port:
                  number: 6060
