# playbooks/argocd/applications/media/booklore/mariadb-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: booklore-mariadb
  namespace: media
  labels:
    app: booklore-mariadb
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    app: booklore-mariadb
