---
- name: Apply Mosquitto
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig_path }}"
    namespace: argocd
    definition: "{{ lookup('file', playbook_dir + '/argocd/applications/home-automation/mosquitto/mosquitto-application.yaml') }}"

