---
- name: Apply Sonarr
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig_path }}"
    namespace: argocd
    definition: "{{ lookup('file', playbook_dir + '/argocd/applications/media/sonarr/sonarr-application.yaml') }}"
  tags: [sonarr]

