apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: obsidian-offsite-backup
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: obsidian
  source:
    repoURL: https://github.com/kpoxo6op/soyspray.git
    targetRevision: "HEAD"
    path: playbooks/argocd/applications/backups/obsidian-offsite-backup
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

