---
- name: Apply Immich Database Active
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig_path }}"
    namespace: argocd
    definition: "{{ lookup('file', playbook_dir + '/argocd/applications/database/cnpg/immich-db-active-application.yaml') }}"
  tags: [immich-db-active]

