# Base kustomization for immich-db Cluster
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgresql
resources:
  - cluster-base.yaml
  - immich-app-secret.yaml
configurations:
  - kustomize-config.yaml

