---
- name: Apply CNPG Operator
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig_path }}"
    namespace: argocd
    definition: "{{ lookup('file', playbook_dir + '/argocd/applications/database/cnpg/cnpg-operator-application.yaml') }}"

