---
- name: Apply Zigbee2MQTT
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig_path }}"
    namespace: argocd
    definition: "{{ lookup('file', playbook_dir + '/argocd/applications/home-automation/zigbee2mqtt/zigbee2mqtt-application.yaml') }}"

