---
- name: Apply Alloy Loki Manual
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig_path }}"
    namespace: argocd
    definition: "{{ lookup('file', playbook_dir + '/argocd/applications/observability/alloy-loki-manual/loki-application.yaml') }}"
  tags: [alloy-loki-manual]

